version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  ordersservice:
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    ports:
      - "5222:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Rabbit__Host=rabbitmq
    depends_on:
      - rabbitmq

  paymentsservice:
    build:
      context: .
      dockerfile: PaymentsService/Dockerfile
    ports:
      - "5075:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Rabbit__Host=rabbitmq
    depends_on:
      - rabbitmq

  apigateway:
    build:
      context: ./ApiGateway
    ports:
      - "5130:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - ordersservice
      - paymentsservice 